### ISSUE TITLE
Error 500 on project view

### ISSUE THREAD

**Issue by platypus-geek** [fraoustin/redmine_indicator#16]
Hello

I've got some issue with the project view and the 3 customs fields like indicator_left_top
I'm using redmine 4.1.1

This is the error :
`Started GET "/projects/psr/settings" for 91.134.143.177 at 2021-06-15 12:23:26 +0200
Processing by ProjectsController#settings as HTML
  Rendering projects/settings.html.erb within layouts/base
  Rendered projects/_form.html.erb (62.7ms)
  Rendered projects/_edit.html.erb (64.6ms)
  Rendered common/_tabs.html.erb (67.9ms)
  Rendered projects/settings.html.erb within layouts/base (72.4ms)
Completed 500 Internal Server Error in 116ms (ActiveRecord: 8.1ms)
  
ActionView::Template::Error (undefined method `indicator_left_top' for #<Project:0x00007f743851a500>
Did you mean?  indicator_left_top_empty):
    28: <% @project.visible_custom_field_values.each do |value| %>
    29:   <p><%= custom_field_tag_with_label :project, value %></p>
    30: <% end %>
    31: <%= call_hook(:view_projects_form, :project => @project, :form => f) %>
    32: </div>
    33: 
    34: <% if @project.safe_attribute?('enabled_module_names') %>
  
lib/redmine/views/labelled_form_builder.rb:40:in `select'
plugins/redmine_indicator/lib/redmine_indicator/project_listener.rb:7:in `view_projects_form'
`

In the setting of project I don't have the 3 custom fields, so i try to add it, but the error is already here.

Is there something I miss ?

Thanks

PS : I saw the closed issue on the same problem. I tried again the installation, and saw an error :

rake aborted!
ActiveRecord::NoDatabaseError: Unknown database 'redmine_development'

Maybe it's a redmine configuration on my side.....

**Comment by platypus-geek** [comment]
It was an environement problème.
The command 
`rake redmine:plugins:migrate NAME=redmine_indicator RAILS_ENV=production `
solved my problem
