### ISSUE TITLE
Cannot define multiple 'included' blocks for a Concern

### ISSUE THREAD

**Issue by devent** [fraoustin/redmine_indicator#20]
Tried the plugin with Redmine 4.2.3, got the error: `Cannot define multiple 'included' blocks for a Concern`

No other plugins are used.

Full log:

```
redmine 19:49:10.34 INFO  ==> Updating admin user credentials
redmine 19:49:10.35 DEBUG ==> Executing SQL command:
UPDATE users SET login = 'user', hashed_password = 'a281f355abfaf059bb96994cc509394d5fb3f75c', salt = 's0YClUWxzmNJHChfcY0CTiirH7c1Lz5G', firstname = 'UserName', lastname = 'LastName', must_change_passwd = '0' WHERE id = '1';
UPDATE email_addresses SET address = 'user@example.com' WHERE id = '1';
redmine 19:49:10.63 INFO  ==> Loading default configuration data
Default configuration data loaded.
redmine 19:49:19.41 INFO  ==> Persisting Redmine installation
redmine 19:49:19.57 INFO  ==> ** Redmine setup finished! **

redmine 19:49:19.62 INFO  ==> ** Starting Redmine **
 [passenger_native_support.so] trying to compile for the current user (root) and Ruby interpreter...
     (set PASSENGER_COMPILE_NATIVE_SUPPORT_BINARY=0 to disable)
     Warning: compilation didn't succeed. To learn why, read this file:
     /tmp/passenger_native_support-1ca0vj0.log
 [passenger_native_support.so] finding downloads for the current Ruby interpreter...
     (set PASSENGER_DOWNLOAD_NATIVE_SUPPORT_BINARY=0 to disable)
     Could not download https://github.com/phusion/passenger/releases/download/release-6.0.12/rubyext-ruby-2.6.9-x86_64-linux.tar.gz: The requested URL returned error: 404 
     Trying next mirror...
     Could not download https://oss-binaries.phusionpassenger.com/binaries/passenger/by_release/6.0.12/rubyext-ruby-2.6.9-x86_64-linux.tar.gz: The requested URL returned error: 404 
     Trying next mirror...
     Could not download https://s3.amazonaws.com/phusion-passenger/binaries/passenger/by_release/6.0.12/rubyext-ruby-2.6.9-x86_64-linux.tar.gz: The requested URL returned error: 403 Forbidden
 [passenger_native_support.so] will not be used (can't compile or download) 
  --> Passenger will still operate normally.
=============== Phusion Passenger(R) Standalone web server started ===============
PID file: /opt/bitnami/redmine/passenger.3000.pid
Log file: /opt/bitnami/redmine/log/passenger.3000.log
Environment: production
Accessible via: http://0.0.0.0:3000/

You can stop Phusion Passenger(R) Standalone by pressing Ctrl-C.
Problems? Check https://www.phusionpassenger.com/library/admin/standalone/troubleshooting/
===============================================================================
[ N 2022-01-30 19:49:24.5884 321/T5 age/Cor/SecurityUpdateChecker.h:519 ]: Security update check: no update found (next check in 24 hours)
App 360 output:  [passenger_native_support.so] trying to compile for the current user (redmine) and Ruby interpreter...
App 360 output:      (set PASSENGER_COMPILE_NATIVE_SUPPORT_BINARY=0 to disable)
App 360 output:      Warning: compilation didn't succeed. To learn why, read this file:
App 360 output:      /tmp/passenger_native_support-198x2ws.log
App 360 output:  [passenger_native_support.so] finding downloads for the current Ruby interpreter...
App 360 output:      (set PASSENGER_DOWNLOAD_NATIVE_SUPPORT_BINARY=0 to disable)
App 360 output:      Could not download https://github.com/phusion/passenger/releases/download/release-6.0.12/rubyext-ruby-2.6.9-x86_64-linux.tar.gz: The requested URL returned error: 404 
App 360 output:      Trying next mirror...
App 360 output:      Could not download https://oss-binaries.phusionpassenger.com/binaries/passenger/by_release/6.0.12/rubyext-ruby-2.6.9-x86_64-linux.tar.gz: The requested URL returned error: 404 
App 360 output:      Trying next mirror...
App 360 output:      Could not download https://s3.amazonaws.com/phusion-passenger/binaries/passenger/by_release/6.0.12/rubyext-ruby-2.6.9-x86_64-linux.tar.gz: The requested URL returned error: 403 Forbidden
App 360 output:  [passenger_native_support.so] will not be used (can't compile or download) 
App 360 output:   --> Passenger will still operate normally.
Creating scope :system. Overwriting existing method Enumeration.system.
Creating scope :sorted. Overwriting existing method Group.sorted.
Creating scope :sorted. Overwriting existing method User.sorted.
App 360 output: /opt/bitnami/redmine/plugins/redmine_indicator/lib/redmine_indicator/project_patch.rb:5: warning: already initialized constant AVAILABLE_REPORTS
App 360 output: /bitnami/redmine/plugins/redmine_indicator/lib/redmine_indicator/project_patch.rb:5: warning: previous definition of AVAILABLE_REPORTS was here
App 360 output: Error: The application encountered the following error: Cannot define multiple 'included' blocks for a Concern (ActiveSupport::Concern::MultipleIncludedBlocks)
App 360 output:     /opt/bitnami/redmine/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.6/lib/active_support/concern.rb:130:in `included'
App 360 output:     /opt/bitnami/redmine/plugins/redmine_indicator/lib/redmine_indicator/project_patch.rb:9:in `<module:ProjectPatch>'
App 360 output:     /opt/bitnami/redmine/plugins/redmine_indicator/lib/redmine_indicator/project_patch.rb:2:in `<module:RedmineIndicator>'
App 360 output:     /opt/bitnami/redmine/plugins/redmine_indicator/lib/redmine_indicator/project_patch.rb:1:in `<top (required)>'
App 360 output:     /opt/bitnami/redmine/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.6/lib/active_support/dependencies.rb:291:in `require'
App 360 output:     /opt/bitnami/redmine/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.6/lib/active_support/dependencies.rb:291:in `block in require'
App 360 output:     /opt/bitnami/redmine/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.6/lib/active_support/dependencies.rb:257:in `load_dependency'
App 360 output:     /opt/bitnami/redmine/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.6/lib/active_support/dependencies.rb:291:in `require'
App 360 output:     /opt/bitnami/redmine/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.6/lib/active_support/dependencies.rb:378:in `block in require_or_load'
App 360 output:     /opt/bitnami/redmine/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.6/lib/active_support/dependencies.rb:37:in `block in load_interlock'
App 360 output:     /opt/bitnami/redmine/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.6/lib/active_support/dependencies/interlock.rb:14:in `block in loading'
App 360 output:     /opt/bitnami/redmine/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.6/lib/active_support/concurrency/share_lock.rb:151:in `exclusive'
App 360 output:     /opt/bitnami/redmine/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.6/lib/active_support/dependencies/interlock.rb:13:in `loading'
App 360 output:     /opt/bitnami/redmine/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.6/lib/active_support/dependencies.rb:37:in `load_interlock'
App 360 output:     /opt/bitnami/redmine/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.6/lib/active_support/dependencies.rb:356:in `require_or_load'
App 360 output:     /opt/bitnami/redmine/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.6/lib/active_support/dependencies.rb:334:in `depend_on'
App 360 output:     /opt/bitnami/redmine/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.6/lib/active_support/dependencies.rb:246:in `require_dependency'
App 360 output:     /opt/bitnami/redmine/vendor/bundle/ruby/2.6.0/gems/railties-5.2.6/lib/rails/engine.rb:478:in `block (2 levels) in eager_load!'
App 360 output:     /opt/bitnami/redmine/vendor/bundle/ruby/2.6.0/gems/railties-5.2.6/lib/rails/engine.rb:477:in `each'
App 360 output:     /opt/bitnami/redmine/vendor/bundle/ruby/2.6.0/gems/railties-5.2.6/lib/rails/engine.rb:477:in `block in eager_load!'
App 360 output:     /opt/bitnami/redmine/vendor/bundle/ruby/2.6.0/gems/railties-5.2.6/lib/rails/engine.rb:475:in `each'
App 360 output:     /opt/bitnami/redmine/vendor/bundle/ruby/2.6.0/gems/railties-5.2.6/lib/rails/engine.rb:475:in `eager_load!'
App 360 output:     /opt/bitnami/redmine/vendor/bundle/ruby/2.6.0/gems/railties-5.2.6/lib/rails/engine.rb:356:in `eager_load!'
App 360 output:     /opt/bitnami/redmine/vendor/bundle/ruby/2.6.0/gems/railties-5.2.6/lib/rails/application/finisher.rb:69:in `each'
App 360 output:     /opt/bitnami/redmine/vendor/bundle/ruby/2.6.0/gems/railties-5.2.6/lib/rails/application/finisher.rb:69:in `block in <module:Finisher>'
App 360 output:     /opt/bitnami/redmine/vendor/bundle/ruby/2.6.0/gems/railties-5.2.6/lib/rails/initializable.rb:32:in `instance_exec'
App 360 output:     /opt/bitnami/redmine/vendor/bundle/ruby/2.6.0/gems/railties-5.2.6/lib/rails/initializable.rb:32:in `run'
App 360 output:     /opt/bitnami/redmine/vendor/bundle/ruby/2.6.0/gems/railties-5.2.6/lib/rails/initializable.rb:61:in `block in run_initializers'
App 360 output:     /opt/bitnami/ruby/lib/ruby/2.6.0/tsort.rb:228:in `block in tsort_each'
App 360 output:     /opt/bitnami/ruby/lib/ruby/2.6.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
App 360 output:     /opt/bitnami/ruby/lib/ruby/2.6.0/tsort.rb:431:in `each_strongly_connected_component_from'
App 360 output:     /opt/bitnami/ruby/lib/ruby/2.6.0/tsort.rb:349:in `block in each_strongly_connected_component'
App 360 output:     /opt/bitnami/ruby/lib/ruby/2.6.0/tsort.rb:347:in `each'
App 360 output:     /opt/bitnami/ruby/lib/ruby/2.6.0/tsort.rb:347:in `call'
App 360 output:     /opt/bitnami/ruby/lib/ruby/2.6.0/tsort.rb:347:in `each_strongly_connected_component'
App 360 output:     /opt/bitnami/ruby/lib/ruby/2.6.0/tsort.rb:226:in `tsort_each'
App 360 output:     /opt/bitnami/ruby/lib/ruby/2.6.0/tsort.rb:205:in `tsort_each'
App 360 output:     /opt/bitnami/redmine/vendor/bundle/ruby/2.6.0/gems/railties-5.2.6/lib/rails/initializable.rb:60:in `run_initializers'
App 360 output:     /opt/bitnami/redmine/vendor/bundle/ruby/2.6.0/gems/railties-5.2.6/lib/rails/application.rb:361:in `initialize!'
App 360 output:     /opt/bitnami/redmine/config/environment.rb:16:in `<top (required)>'
App 360 output:     config.ru:3:in `require'
App 360 output:     config.ru:3:in `block in <main>'
App 360 output:     /opt/bitnami/redmine/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/builder.rb:125:in `instance_eval'
App 360 output:     /opt/bitnami/redmine/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/builder.rb:125:in `initialize'
App 360 output:     config.ru:1:in `new'
App 360 output:     config.ru:1:in `<main>'
App 360 output:     /opt/bitnami/redmine/vendor/bundle/ruby/2.6.0/gems/passenger-6.0.12/src/helper-scripts/rack-preloader.rb:101:in `eval'
App 360 output:     /opt/bitnami/redmine/vendor/bundle/ruby/2.6.0/gems/passenger-6.0.12/src/helper-scripts/rack-preloader.rb:101:in `preload_app'
App 360 output:     /opt/bitnami/redmine/vendor/bundle/ruby/2.6.0/gems/passenger-6.0.12/src/helper-scripts/rack-preloader.rb:189:in `block in <module:App>'
App 360 output:     /opt/bitnami/redmine/vendor/bundle/ruby/2.6.0/gems/passenger-6.0.12/src/ruby_supportlib/phusion_passenger/loader_shared_helpers.rb:397:in `run_block_and_record_step_progress'
App 360 output:     /opt/bitnami/redmine/vendor/bundle/ruby/2.6.0/gems/passenger-6.0.12/src/helper-scripts/rack-preloader.rb:188:in `<module:App>'
App 360 output:     /opt/bitnami/redmine/vendor/bundle/ruby/2.6.0/gems/passenger-6.0.12/src/helper-scripts/rack-preloader.rb:30:in `<module:PhusionPassenger>'
App 360 output:     /opt/bitnami/redmine/vendor/bundle/ruby/2.6.0/gems/passenger-6.0.12/src/helper-scripts/rack-preloader.rb:29:in `<main>'
[ E 2022-01-30 19:49:28.7741 321/Tj age/Cor/App/Implementation.cpp:221 ]: Could not spawn process for application /opt/bitnami/redmine: The application encountered the following error: Cannot define multiple 'included' blocks for a Concern (ActiveSupport::Concern::MultipleIncludedBlocks)
  Error ID: 1f2efd75
  Error details saved to: /tmp/passenger-error-VKJV2C.html

[ E 2022-01-30 19:49:28.7780 321/T8 age/Cor/Con/CheckoutSession.cpp:283 ]: [Client 1-1] Cannot checkout session because a spawning error occurred. The identifier of the error is 1f2efd75. Please see earlier logs for details about the error.
```

**Comment by fraoustin** [comment]
I check the last version (4.2.3.stable) with docker

My Dockerfile is

```
FROM redmine
WORKDIR /usr/src/redmine/plugins
RUN git clone https://github.com/fraoustin/redmine_indicator.git
WORKDIR /usr/src/redmine/
```
and load with

```
docker build -t myredmine .
docker run -d -p 3000:3000 -e REDMINE_PLUGINS_MIGRATE=1 --name myredmine myredmine
```

And all it's ok ...

How do you install redmine?

**Comment by devent** [comment]
I'm using the Bitnami Docker build. https://hub.docker.com/r/bitnami/redmine Tag `bitnami/redmine:4.2.3-debian-10-r101`
Just downloaded from Github master branch, unpack and add the directory `redmine_indicator` to `/opt/bitnami/redmine/plugins`
It works for all other plugins.

Log of build:

```
Step 1/4 : FROM bitnami/redmine:4.2.3-debian-10-r101
 ---> 05519cbad099
Step 2/4 : LABEL maintainer "Erwin Mueller <erwin@muellerpublic.de>"
 ---> Using cache
 ---> 006475a76b90
Step 3/4 : ADD rootfs /opt/bitnami/redmine
 ---> 437b6e02fd65
Step 4/4 : RUN set -e &&   chown redmine.root -R /opt/bitnami/redmine/plugins &&   chown redmine.root -R /opt/bitnami/redmine/public/themes &&   ls -l /opt/bitnami/redmine/plugins &&   ls -l /opt/bitnami/redmine/public/themes &&   gosu redmine bash -c "cd /opt/bitnami/redmine;    . /opt/bitnami/scripts/redmine-env.sh;    . /opt/bitnami/scripts/libvalidations.sh;    bundle config unset deployment;    bundle install;"
 ---> Running in 40e9852dc731
total 12
-rw-rw-r-- 1 redmine root   31 Jan 24 17:52 README
drwxrwxr-x 1 redmine root 4096 Aug 25  2020 redmine_indicator
total 36
-rw-rw-r-- 1 redmine root   30 Jan 24 17:52 README
drwxrwxr-x 1 redmine root 4096 Jan 24 20:48 alternate
drwxrwxr-x 1 redmine root 4096 Jan 24 17:27 bleuclair
drwxrwxr-x 1 redmine root 4096 Jan 24 20:48 classic
drwxrwxr-x 1 redmine root 4096 Sep  9 22:21 minimalflat
Bundler 2.3.5 is running, but your lockfile was generated with 2.2.22. Installing Bundler 2.2.22 and restarting using that version.
Fetching gem metadata from https://rubygems.org/.
Fetching bundler 2.2.22
Installing bundler 2.2.22
Using rake 13.0.6
Using concurrent-ruby 1.1.9
Using i18n 1.8.11
Using minitest 5.15.0
Using thread_safe 0.3.6
Using tzinfo 1.2.9
Using activesupport 5.2.6
Using builder 3.2.4
Using erubi 1.10.0
Using racc 1.6.0
Using nokogiri 1.11.7 (x86_64-linux)
Using rails-dom-testing 2.0.3
Using crass 1.0.6
Using loofah 2.13.0
Using rails-html-sanitizer 1.4.2
Using actionview 5.2.6
Using rack 2.2.3
Using rack-test 1.1.0
Using actionpack 5.2.6
Using nio4r 2.5.8
Using websocket-extensions 0.1.5
Using websocket-driver 0.7.5
Using actioncable 5.2.6
Using globalid 1.0.0
Using activejob 5.2.6
Using mini_mime 1.0.3
Using mail 2.7.1
Using actionmailer 5.2.6
Using method_source 1.0.0
Using thor 1.2.1
Using railties 5.2.6
Using actionpack-xml_parser 2.0.1
Using activemodel 5.2.6
Using arel 9.0.0
Using activerecord 5.2.6
Using marcel 1.0.2
Using activestorage 5.2.6
Using public_suffix 4.0.6
Using addressable 2.8.0
Using bundler 2.2.22
Using chunky_png 1.4.0
Using css_parser 1.11.0
Using csv 3.1.9
Using htmlentities 4.3.4
Using mini_magick 4.11.0
Using mysql2 0.5.3
Using net-ldap 0.17.0
Using passenger 6.0.12
Using pg 1.2.3
Using ruby-openid 2.9.2
Using rack-openid 1.4.2
Using sprockets 4.0.2
Using sprockets-rails 3.4.2
Using rails 5.2.6
Using rbpdf-font 1.19.1
Using rbpdf 1.20.1
Using redcarpet 3.5.1
Using request_store 1.5.1
Using roadie 4.0.0
Using roadie-rails 2.2.0
Using rotp 6.2.0
Using rouge 3.26.1
Using rqrcode_core 1.2.0
Using rqrcode 2.1.0
Using rubyzip 2.3.2
Bundle complete! 38 Gemfile dependencies, 65 gems now installed.
Gems in the groups 'development', 'sqlite' and 'test' were not installed.
Bundled gems are installed into `./vendor/bundle`
Removing intermediate container 40e9852dc731
 ---> 6e4ac75c2e05
Successfully built 6e4ac75c2e05
```

**Comment by devent** [comment]
Here is the log:

```
[migrations]
redmine 15:55:35.64 INFO  ==> Updating admin user credentials
redmine 15:55:35.64 DEBUG ==> Executing SQL command:
UPDATE users SET login = 'user', hashed_password = '7715ad194243c1260de77619c46a89b5122eb02b', salt = 'F0ntS46Odqs09EiNfrE8jvkNGAWCnAOp', firstname = 'UserName', lastname = 'LastName', must_change_passwd = '0' WHERE id = '1';
UPDATE email_addresses SET address = 'user@example.com' WHERE id = '1';
redmine 15:55:36.79 INFO  ==> Loading default configuration data
Default configuration data loaded.
redmine 15:55:42.47 INFO  ==> Persisting Redmine installation
redmine 15:55:42.59 INFO  ==> ** Redmine setup finished! **

redmine 15:55:42.63 INFO  ==> ** Starting Redmine **
 [passenger_native_support.so] trying to compile for the current user (root) and Ruby interpreter...
     (set PASSENGER_COMPILE_NATIVE_SUPPORT_BINARY=0 to disable)
     Warning: compilation didn't succeed. To learn why, read this file:
     /tmp/passenger_native_support-1itkzj.log
 [passenger_native_support.so] finding downloads for the current Ruby interpreter...
     (set PASSENGER_DOWNLOAD_NATIVE_SUPPORT_BINARY=0 to disable)
     Could not download https://github.com/phusion/passenger/releases/download/release-6.0.12/rubyext-ruby-2.6.9-x86_64-linux.tar.gz: The requested URL returned error: 404 
     Trying next mirror...
     Could not download https://oss-binaries.phusionpassenger.com/binaries/passenger/by_release/6.0.12/rubyext-ruby-2.6.9-x86_64-linux.tar.gz: The requested URL returned error: 404 
     Trying next mirror...
     Could not download https://s3.amazonaws.com/phusion-passenger/binaries/passenger/by_release/6.0.12/rubyext-ruby-2.6.9-x86_64-linux.tar.gz: The requested URL returned error: 403 Forbidden
 [passenger_native_support.so] will not be used (can't compile or download) 
  --> Passenger will still operate normally.
=============== Phusion Passenger(R) Standalone web server started ===============
PID file: /opt/bitnami/redmine/passenger.3000.pid
Log file: /opt/bitnami/redmine/log/passenger.3000.log
Environment: production
Accessible via: http://0.0.0.0:3000/

You can stop Phusion Passenger(R) Standalone by pressing Ctrl-C.
Problems? Check https://www.phusionpassenger.com/library/admin/standalone/troubleshooting/
===============================================================================
[ N 2022-01-31 15:55:46.9460 330/T5 age/Cor/SecurityUpdateChecker.h:519 ]: Security update check: no update found (next check in 24 hours)
App 369 output:  [passenger_native_support.so] trying to compile for the current user (redmine) and Ruby interpreter...
App 369 output:      (set PASSENGER_COMPILE_NATIVE_SUPPORT_BINARY=0 to disable)
App 369 output:      Warning: compilation didn't succeed. To learn why, read this file:
App 369 output:      /tmp/passenger_native_support-3j18ar.log
App 369 output:  [passenger_native_support.so] finding downloads for the current Ruby interpreter...
App 369 output:      (set PASSENGER_DOWNLOAD_NATIVE_SUPPORT_BINARY=0 to disable)
App 369 output:      Could not download https://github.com/phusion/passenger/releases/download/release-6.0.12/rubyext-ruby-2.6.9-x86_64-linux.tar.gz: The requested URL returned error: 404 
App 369 output:      Trying next mirror...
App 369 output:      Could not download https://oss-binaries.phusionpassenger.com/binaries/passenger/by_release/6.0.12/rubyext-ruby-2.6.9-x86_64-linux.tar.gz: The requested URL returned error: 404 
App 369 output:      Trying next mirror...
App 369 output:      Could not download https://s3.amazonaws.com/phusion-passenger/binaries/passenger/by_release/6.0.12/rubyext-ruby-2.6.9-x86_64-linux.tar.gz: The requested URL returned error: 403 Forbidden
App 369 output:  [passenger_native_support.so] will not be used (can't compile or download) 
App 369 output:   --> Passenger will still operate normally.
Creating scope :system. Overwriting existing method Enumeration.system.
Creating scope :sorted. Overwriting existing method Group.sorted.
Creating scope :sorted. Overwriting existing method User.sorted.
App 369 output: /opt/bitnami/redmine/plugins/redmine_indicator/lib/redmine_indicator/project_patch.rb:5: warning: already initialized constant AVAILABLE_REPORTS
App 369 output: /bitnami/redmine/plugins/redmine_indicator/lib/redmine_indicator/project_patch.rb:5: warning: previous definition of AVAILABLE_REPORTS was here
App 369 output: Error: The application encountered the following error: Cannot define multiple 'included' blocks for a Concern (ActiveSupport::Concern::MultipleIncludedBlocks)
App 369 output:     /opt/bitnami/redmine/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.6/lib/active_support/concern.rb:130:in `included'
App 369 output:     /opt/bitnami/redmine/plugins/redmine_indicator/lib/redmine_indicator/project_patch.rb:9:in `<module:ProjectPatch>'
App 369 output:     /opt/bitnami/redmine/plugins/redmine_indicator/lib/redmine_indicator/project_patch.rb:2:in `<module:RedmineIndicator>'
App 369 output:     /opt/bitnami/redmine/plugins/redmine_indicator/lib/redmine_indicator/project_patch.rb:1:in `<top (required)>'
App 369 output:     /opt/bitnami/redmine/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.6/lib/active_support/dependencies.rb:291:in `require'
App 369 output:     /opt/bitnami/redmine/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.6/lib/active_support/dependencies.rb:291:in `block in require'
App 369 output:     /opt/bitnami/redmine/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.6/lib/active_support/dependencies.rb:257:in `load_dependency'
App 369 output:     /opt/bitnami/redmine/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.6/lib/active_support/dependencies.rb:291:in `require'
App 369 output:     /opt/bitnami/redmine/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.6/lib/active_support/dependencies.rb:378:in `block in require_or_load'
App 369 output:     /opt/bitnami/redmine/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.6/lib/active_support/dependencies.rb:37:in `block in load_interlock'
App 369 output:     /opt/bitnami/redmine/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.6/lib/active_support/dependencies/interlock.rb:14:in `block in loading'
App 369 output:     /opt/bitnami/redmine/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.6/lib/active_support/concurrency/share_lock.rb:151:in `exclusive'
App 369 output:     /opt/bitnami/redmine/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.6/lib/active_support/dependencies/interlock.rb:13:in `loading'
App 369 output:     /opt/bitnami/redmine/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.6/lib/active_support/dependencies.rb:37:in `load_interlock'
App 369 output:     /opt/bitnami/redmine/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.6/lib/active_support/dependencies.rb:356:in `require_or_load'
App 369 output:     /opt/bitnami/redmine/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.6/lib/active_support/dependencies.rb:334:in `depend_on'
App 369 output:     /opt/bitnami/redmine/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.6/lib/active_support/dependencies.rb:246:in `require_dependency'
App 369 output:     /opt/bitnami/redmine/vendor/bundle/ruby/2.6.0/gems/railties-5.2.6/lib/rails/engine.rb:478:in `block (2 levels) in eager_load!'
App 369 output:     /opt/bitnami/redmine/vendor/bundle/ruby/2.6.0/gems/railties-5.2.6/lib/rails/engine.rb:477:in `each'
App 369 output:     /opt/bitnami/redmine/vendor/bundle/ruby/2.6.0/gems/railties-5.2.6/lib/rails/engine.rb:477:in `block in eager_load!'
App 369 output:     /opt/bitnami/redmine/vendor/bundle/ruby/2.6.0/gems/railties-5.2.6/lib/rails/engine.rb:475:in `each'
App 369 output:     /opt/bitnami/redmine/vendor/bundle/ruby/2.6.0/gems/railties-5.2.6/lib/rails/engine.rb:475:in `eager_load!'
App 369 output:     /opt/bitnami/redmine/vendor/bundle/ruby/2.6.0/gems/railties-5.2.6/lib/rails/engine.rb:356:in `eager_load!'
App 369 output:     /opt/bitnami/redmine/vendor/bundle/ruby/2.6.0/gems/railties-5.2.6/lib/rails/application/finisher.rb:69:in `each'
App 369 output:     /opt/bitnami/redmine/vendor/bundle/ruby/2.6.0/gems/railties-5.2.6/lib/rails/application/finisher.rb:69:in `block in <module:Finisher>'
App 369 output:     /opt/bitnami/redmine/vendor/bundle/ruby/2.6.0/gems/railties-5.2.6/lib/rails/initializable.rb:32:in `instance_exec'
App 369 output:     /opt/bitnami/redmine/vendor/bundle/ruby/2.6.0/gems/railties-5.2.6/lib/rails/initializable.rb:32:in `run'
App 369 output:     /opt/bitnami/redmine/vendor/bundle/ruby/2.6.0/gems/railties-5.2.6/lib/rails/initializable.rb:61:in `block in run_initializers'
App 369 output:     /opt/bitnami/ruby/lib/ruby/2.6.0/tsort.rb:228:in `block in tsort_each'
App 369 output:     /opt/bitnami/ruby/lib/ruby/2.6.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
App 369 output:     /opt/bitnami/ruby/lib/ruby/2.6.0/tsort.rb:431:in `each_strongly_connected_component_from'
App 369 output:     /opt/bitnami/ruby/lib/ruby/2.6.0/tsort.rb:349:in `block in each_strongly_connected_component'
App 369 output:     /opt/bitnami/ruby/lib/ruby/2.6.0/tsort.rb:347:in `each'
App 369 output:     /opt/bitnami/ruby/lib/ruby/2.6.0/tsort.rb:347:in `call'
App 369 output:     /opt/bitnami/ruby/lib/ruby/2.6.0/tsort.rb:347:in `each_strongly_connected_component'
App 369 output:     /opt/bitnami/ruby/lib/ruby/2.6.0/tsort.rb:226:in `tsort_each'
App 369 output:     /opt/bitnami/ruby/lib/ruby/2.6.0/tsort.rb:205:in `tsort_each'
App 369 output:     /opt/bitnami/redmine/vendor/bundle/ruby/2.6.0/gems/railties-5.2.6/lib/rails/initializable.rb:60:in `run_initializers'
App 369 output:     /opt/bitnami/redmine/vendor/bundle/ruby/2.6.0/gems/railties-5.2.6/lib/rails/application.rb:361:in `initialize!'
App 369 output:     /opt/bitnami/redmine/config/environment.rb:16:in `<top (required)>'
App 369 output:     config.ru:3:in `require'
App 369 output:     config.ru:3:in `block in <main>'
App 369 output:     /opt/bitnami/redmine/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/builder.rb:125:in `instance_eval'
App 369 output:     /opt/bitnami/redmine/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/builder.rb:125:in `initialize'
App 369 output:     config.ru:1:in `new'
App 369 output:     config.ru:1:in `<main>'
App 369 output:     /opt/bitnami/redmine/vendor/bundle/ruby/2.6.0/gems/passenger-6.0.12/src/helper-scripts/rack-preloader.rb:101:in `eval'
App 369 output:     /opt/bitnami/redmine/vendor/bundle/ruby/2.6.0/gems/passenger-6.0.12/src/helper-scripts/rack-preloader.rb:101:in `preload_app'
App 369 output:     /opt/bitnami/redmine/vendor/bundle/ruby/2.6.0/gems/passenger-6.0.12/src/helper-scripts/rack-preloader.rb:189:in `block in <module:App>'
App 369 output:     /opt/bitnami/redmine/vendor/bundle/ruby/2.6.0/gems/passenger-6.0.12/src/ruby_supportlib/phusion_passenger/loader_shared_helpers.rb:397:in `run_block_and_record_step_progress'
App 369 output:     /opt/bitnami/redmine/vendor/bundle/ruby/2.6.0/gems/passenger-6.0.12/src/helper-scripts/rack-preloader.rb:188:in `<module:App>'
App 369 output:     /opt/bitnami/redmine/vendor/bundle/ruby/2.6.0/gems/passenger-6.0.12/src/helper-scripts/rack-preloader.rb:30:in `<module:PhusionPassenger>'
App 369 output:     /opt/bitnami/redmine/vendor/bundle/ruby/2.6.0/gems/passenger-6.0.12/src/helper-scripts/rack-preloader.rb:29:in `<main>'
[ E 2022-01-31 15:55:52.9075 330/Tj age/Cor/App/Implementation.cpp:221 ]: Could not spawn process for application /opt/bitnami/redmine: The application encountered the following error: Cannot define multiple 'included' blocks for a Concern (ActiveSupport::Concern::MultipleIncludedBlocks)
  Error ID: f75e518b
  Error details saved to: /tmp/passenger-error-kaLqOL.html

[ E 2022-01-31 15:55:52.9154 330/T9 age/Cor/Con/CheckoutSession.cpp:283 ]: [Client 1-1] Cannot checkout session because a spawning error occurred. The identifier of the error is f75e518b. Please see earlier logs for details about the error.
```

**Comment by fraoustin** [comment]
The problem form a specific verrsion of redmine ... the problem from Concern
